### ISSUE TITLE
[失敗] default namespace的流量開放解決方案

### ISSUE THREAD

**Issue by Vinskao** [Distributed-System-Design-Lab/member-service-authorization-server#1]
# 目標設置邏輯
1. 外部流量經由 OCI Load Balancer (150.230.6.62):
- 所有外部的請求都進入該 IP。
- 該 IP 綁定到 NGINX Controller 的 LoadBalancer Service。

2. NGINX Controller 轉發流量到 Istio Ingress Gateway:
NGINX 作為第一層入口控制器（L7代理），接收流量後按照配置的路由（例如基於 Host 或 Path 的路由）將流量轉發給 Istio。

3. Istio Gateway 和 VirtualService 根據路由規則處理流量，轉發到後端服務。

**Comment by Vinskao** [comment]
## 1. 配置 NGINX Ingress Controller 與 OCI Load Balancer
修改 NGINX Ingress Controller 的 Service，綁定到 OCI 的 Reserved IP：

```bash
kubectl get svc -n ingress-nginx 
kubectl edit svc ingress-nginx-controller -n ingress-nginx
```
```yaml
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: 10Mbps
    service.beta.kubernetes.io/oci-load-balancer-reserved-ip: "150.230.6.62"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
    - port: 443
      targetPort: 443
      protocol: TCP
  selector:
    app.kubernetes.io/name: ingress-nginx
```

## 2. 配置 NGINX 將流量轉發到 Istio Controller
編輯 NGINX Ingress 資源，添加轉發到 Istio 的規則：

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: ingress-nginx
spec:
  rules:
  - host: peoplesystem.tatdvsonorth.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ingress-nginx-controller
            port:
              number: 80

```

## 3. 配置 Istio Gateway 與 VirtualService
配置 Istio Gateway，使其處理從 NGINX 轉發的流量：
kubectl get svc -n istio-system
kubectl edit svc istio-ingressgateway -n istio-system

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: peoplesystem-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - peoplesystem.tatdvsonorth.com
```
```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: peoplesystem-vs
  namespace: istio-system
spec:
  hosts:
  - peoplesystem.tatdvsonorth.com
  gateways:
  - peoplesystem-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: member-service-authorization-server.default.svc.cluster.local
        port:
          number: 8080

```
